---
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  podSubnet: "10.4.0.0/16"
  serviceSubnet: "10.6.0.0/16"
nodes:
- role: worker
  image: kindest/node:v1.27.13
- role: worker
  image: kindest/node:v1.27.13
- role: control-plane
  image: kindest/node:v1.27.13
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
  extraPortMappings:
  - containerPort: 32080
    hostPort: 80
    protocol: TCP
  - containerPort: 32443
    hostPort: 443
    protocol: TCP
